"""empty message

Revision ID: c8187bd92fcb
Revises: 
Create Date: 2018-10-30 08:58:23.836991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8187bd92fcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('dre', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('dre'),
    sa.UniqueConstraint('dre')
    )
    op.create_table('pedido',
    sa.Column('dre', sa.String(length=11), nullable=True),
    sa.Column('pedido', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pedido')
    )
    op.create_table('professores',
    sa.Column('siape', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('siape'),
    sa.UniqueConstraint('siape')
    )
    op.create_table('relSalaEAluno',
    sa.Column('dre', sa.String(length=11), nullable=True),
    sa.Column('cod_sala', sa.String(length=5), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salas',
    sa.Column('siape', sa.String(length=11), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('cod_sala', sa.String(length=5), nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cod_sala'),
    sa.UniqueConstraint('cod_sala')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salas')
    op.drop_table('relSalaEAluno')
    op.drop_table('professores')
    op.drop_table('pedido')
    op.drop_table('alunos')
    # ### end Alembic commands ###
